export interface SeedStudent {
  lastName: string;
  firstName: string;
}

export interface SeedClass {
  id: string;
  name: string;
  isMyClass: boolean;
  students: SeedStudent[];
}

export const seedClasses: SeedClass[] = [
  {
    id: "class-7a",
    name: "7А",
    isMyClass: false,
    students: [
      { lastName: "Иванов", firstName: "Алексей" },
      { lastName: "Петрова", firstName: "Мария" },
      { lastName: "Сидоров", firstName: "Дмитрий" },
      { lastName: "Кузнецова", firstName: "Анна" },
      { lastName: "Смирнов", firstName: "Никита" },
      { lastName: "Волкова", firstName: "Елизавета" },
      { lastName: "Козлов", firstName: "Артём" },
      { lastName: "Морозова", firstName: "Дарья" },
      { lastName: "Лебедев", firstName: "Максим" },
      { lastName: "Новикова", firstName: "Полина" },
      { lastName: "Егоров", firstName: "Кирилл" },
      { lastName: "Павлова", firstName: "София" },
      { lastName: "Соколов", firstName: "Иван" },
      { lastName: "Михайлова", firstName: "Алиса" },
      { lastName: "Фёдоров", firstName: "Матвей" },
    ],
  },
  {
    id: "class-7b",
    name: "7Б",
    isMyClass: true,
    students: [
      { lastName: "Соколов", firstName: "Артём" },
      { lastName: "Морозова", firstName: "Дарья" },
      { lastName: "Лебедев", firstName: "Максим" },
      { lastName: "Новикова", firstName: "Полина" },
      { lastName: "Егоров", firstName: "Кирилл" },
      { lastName: "Павлова", firstName: "София" },
      { lastName: "Козлов", firstName: "Иван" },
      { lastName: "Степанова", firstName: "Виктория" },
      { lastName: "Николаев", firstName: "Егор" },
      { lastName: "Орлова", firstName: "Алиса" },
      { lastName: "Фёдоров", firstName: "Матвей" },
      { lastName: "Андреева", firstName: "Ксения" },
      { lastName: "Михайлов", firstName: "Роман" },
      { lastName: "Захарова", firstName: "Ева" },
      { lastName: "Виноградов", firstName: "Тимофей" },
    ],
  },
  {
    id: "class-8a",
    name: "8А",
    isMyClass: false,
    students: [
      { lastName: "Козлов", firstName: "Иван" },
      { lastName: "Степанова", firstName: "Виктория" },
      { lastName: "Николаев", firstName: "Егор" },
      { lastName: "Орлова", firstName: "Алиса" },
      { lastName: "Фёдоров", firstName: "Матвей" },
      { lastName: "Андреева", firstName: "Ксения" },
      { lastName: "Михайлов", firstName: "Роман" },
      { lastName: "Захарова", firstName: "Ева" },
      { lastName: "Виноградов", firstName: "Тимофей" },
      { lastName: "Богданова", firstName: "Милана" },
      { lastName: "Гусев", firstName: "Лев" },
      { lastName: "Комарова", firstName: "Вероника" },
      { lastName: "Белов", firstName: "Александр" },
      { lastName: "Тихонова", firstName: "Арина" },
      { lastName: "Жуков", firstName: "Марк" },
    ],
  },
  {
    id: "class-8b",
    name: "8Б",
    isMyClass: false,
    students: [
      { lastName: "Михайлов", firstName: "Роман" },
      { lastName: "Захарова", firstName: "Ева" },
      { lastName: "Виноградов", firstName: "Тимофей" },
      { lastName: "Богданова", firstName: "Милана" },
      { lastName: "Гусев", firstName: "Лев" },
      { lastName: "Комарова", firstName: "Вероника" },
      { lastName: "Белов", firstName: "Александр" },
      { lastName: "Тихонова", firstName: "Арина" },
      { lastName: "Жуков", firstName: "Марк" },
      { lastName: "Крылова", firstName: "Варвара" },
      { lastName: "Соловьёв", firstName: "Даниил" },
      { lastName: "Ершова", firstName: "Таисия" },
      { lastName: "Иванов", firstName: "Пётр" },
      { lastName: "Петрова", firstName: "Анна" },
      { lastName: "Сидоров", firstName: "Максим" },
    ],
  },
  {
    id: "class-9a",
    name: "9А",
    isMyClass: false,
    students: [
      { lastName: "Белов", firstName: "Александр" },
      { lastName: "Тихонова", firstName: "Арина" },
      { lastName: "Жуков", firstName: "Марк" },
      { lastName: "Крылова", firstName: "Варвара" },
      { lastName: "Соловьёв", firstName: "Даниил" },
      { lastName: "Ершова", firstName: "Таисия" },
      { lastName: "Иванов", firstName: "Пётр" },
      { lastName: "Петрова", firstName: "Анна" },
      { lastName: "Сидоров", firstName: "Максим" },
      { lastName: "Кузнецова", firstName: "Ольга" },
      { lastName: "Смирнов", firstName: "Владимир" },
      { lastName: "Волкова", firstName: "Наталья" },
      { lastName: "Егоров", firstName: "Сергей" },
      { lastName: "Павлова", firstName: "Екатерина" },
      { lastName: "Соколов", firstName: "Андрей" },
    ],
  },
  {
    id: "class-9b",
    name: "9Б",
    isMyClass: false,
    students: [
      { lastName: "Крылова", firstName: "Варвара" },
      { lastName: "Соловьёв", firstName: "Даниил" },
      { lastName: "Ершова", firstName: "Таисия" },
      { lastName: "Иванов", firstName: "Пётр" },
      { lastName: "Петрова", firstName: "Анна" },
      { lastName: "Сидоров", firstName: "Максим" },
      { lastName: "Кузнецова", firstName: "Ольга" },
      { lastName: "Смирнов", firstName: "Владимир" },
      { lastName: "Волкова", firstName: "Наталья" },
      { lastName: "Егоров", firstName: "Сергей" },
      { lastName: "Павлова", firstName: "Екатерина" },
      { lastName: "Соколов", firstName: "Андрей" },
      { lastName: "Морозов", firstName: "Дмитрий" },
      { lastName: "Лебедева", firstName: "Ирина" },
      { lastName: "Новиков", firstName: "Павел" },
    ],
  },
  {
    id: "class-10a",
    name: "10А",
    isMyClass: false,
    students: [
      { lastName: "Иванов", firstName: "Пётр" },
      { lastName: "Петрова", firstName: "Анна" },
      { lastName: "Сидоров", firstName: "Максим" },
      { lastName: "Кузнецова", firstName: "Ольга" },
      { lastName: "Смирнов", firstName: "Владимир" },
      { lastName: "Волкова", firstName: "Наталья" },
      { lastName: "Егоров", firstName: "Сергей" },
      { lastName: "Павлова", firstName: "Екатерина" },
      { lastName: "Соколов", firstName: "Андрей" },
      { lastName: "Морозов", firstName: "Дмитрий" },
      { lastName: "Лебедева", firstName: "Ирина" },
      { lastName: "Новиков", firstName: "Павел" },
      { lastName: "Козлов", firstName: "Николай" },
      { lastName: "Степанова", firstName: "Татьяна" },
      { lastName: "Николаев", firstName: "Артём" },
    ],
  },
  {
    id: "class-11a",
    name: "11А",
    isMyClass: false,
    students: [
      { lastName: "Кузнецова", firstName: "Ольга" },
      { lastName: "Смирнов", firstName: "Владимир" },
      { lastName: "Волкова", firstName: "Наталья" },
      { lastName: "Егоров", firstName: "Сергей" },
      { lastName: "Павлова", firstName: "Екатерина" },
      { lastName: "Соколов", firstName: "Андрей" },
      { lastName: "Морозов", firstName: "Дмитрий" },
      { lastName: "Лебедева", firstName: "Ирина" },
      { lastName: "Новиков", firstName: "Павел" },
      { lastName: "Козлов", firstName: "Николай" },
      { lastName: "Степанова", firstName: "Татьяна" },
      { lastName: "Николаев", firstName: "Артём" },
      { lastName: "Орлов", firstName: "Денис" },
      { lastName: "Фёдорова", firstName: "Марина" },
      { lastName: "Андреев", firstName: "Кирилл" },
    ],
  },
];
